apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: ${NAMESPACE:-pypi-test}
spec:
  revisionHistoryLimit: 10
  replicas: 1
  template:
    metadata:
      labels:
        name: worker
    spec:
      containers:
        - name: worker
          image: ${IMAGE_PREFIX}/${NAME}-src:${VERSION:latest}
          command: ["hupper", "-m", "celery", "-A", "warehouse", "worker", "-B", "-S", "redbeat.RedBeatScheduler", "-l", "info", "-c", "1"]
          envFrom:
          - configMapRef:
              name: config
          env:
            - name: C_FORCE_ROOT
              value: "1"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: url
            - name: ELASTICSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: elasticsearch
                  key: url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: aws-secret-access-key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: aws-default-region
          # livenessProbe:
          #   httpGet:
          #     path: /_health/
          #     port: 8000
          # readinessProbe:
          #   httpGet:
          #     path: /_health/
          #     port: 8000
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 1024Mi
