apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: camo
  namespace: ${NAMESPACE:-pypi-test}
spec:
  revisionHistoryLimit: 10
  replicas: 2
  template:
    metadata:
      labels:
        name: camo
    spec:
      containers:
        - name: camo
          image: pypa/warehouse-camo:latest
          env:
            - name: CAMO_KEY
              value: "insecure camo key"
          livenessProbe:
            httpGet:
              path: /
              port: 9000
          readinessProbe:
            httpGet:
              path: /
              port: 9000
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 512Mi
